### ISSUE TITLE
打包成exe打开报错

### ISSUE THREAD

**Issue by hz5453** [Ailln/cn2an#64]
python  打包成 .exe 后的开报错：
Traceback (most recent call last):
  File "gdclient.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "cn2an\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "cn2an\cn2an.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "proces\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "proces\masking.py", line 5, in <module>
  File "proces\util\data.py", line 103, in get_city_pattern
  File "proces\util\data.py", line 10, in get_all_cities
  File "proces\util\conf.py", line 10, in get_yaml
  File "pkg_resources\__init__.py", line 1160, in resource_stream
  File "pkg_resources\__init__.py", line 1409, in get_resource_stream
  File "pkg_resources\__init__.py", line 1412, in get_resource_string
  File "pkg_resources\__init__.py", line 1579, in _get
  File "PyInstaller\loader\pyimod02_importers.py", line 205, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI272522\\proces\\data\\province_city.yaml'

**Comment by hz5453** [comment]
发错了，重发一次。
python  打包成 .exe 后的开报错：
Traceback (most recent call last):
  File "gdclient.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "cn2an\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "cn2an\cn2an.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "proces\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "proces\masking.py", line 5, in <module>
  File "proces\util\data.py", line 103, in get_city_pattern
  File "proces\util\data.py", line 10, in get_all_cities
  File "proces\util\conf.py", line 10, in get_yaml
  File "pkg_resources\__init__.py", line 1160, in resource_stream
  File "pkg_resources\__init__.py", line 1409, in get_resource_stream
  File "pkg_resources\__init__.py", line 1412, in get_resource_string
  File "pkg_resources\__init__.py", line 1579, in _get
  File "PyInstaller\loader\pyimod02_importers.py", line 205, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI272522\\proces\\data\\province_city.yaml'

**Comment by Ailln** [comment]
依赖包的问题，下个小版本修复。

**Comment by Ailln** [comment]
把依赖更新为 `proces>=0.1.7`
